version: "3.8"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgresql.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgresql

volumes:
  mysql-data:
    name: mysql-data
  postgresql-data:
    name: postgresql-data
